
package InterfazGrafica;
import java.awt.*;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

import javax.swing.JLabel;

import Usuarios.GestorUsuarios;
import Usuarios.Usuario;


/**
 *
 * @author Usuario
 */
public class PanelPerfilAdmin extends Panel {

    private MainFrame mainFrame;
    private GestorUsuarios gestorUsuarios;
    private Usuario usuarioSeleccioando;
    private int j;

    public PanelPerfilAdmin(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        gestorUsuarios = new GestorUsuarios();
        usuarioSeleccioando = null;
        j=0;
        initComponents();
        j = cargarUsuariosLista(j);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        background = new javax.swing.JPanel();
        panelUsuario = new javax.swing.JPanel();
        Usuario1 = new javax.swing.JLabel();
        Usuario2 = new javax.swing.JLabel();
        Usuario3 = new javax.swing.JLabel();
        Usuario4 = new javax.swing.JLabel();
        Usuario5 = new javax.swing.JLabel();
        Usuario6 = new javax.swing.JLabel();
        Usuario7 = new javax.swing.JLabel();
        Usuario8 = new javax.swing.JLabel();
        flechaCargarUsuarios = new javax.swing.JLabel();
        seleccionarUsuario = new javax.swing.JTextField();
        usuarioSeleccionado = new javax.swing.JLabel();
        darDeBajaButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrarSesionButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        background.setBackground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        background.setPreferredSize(new java.awt.Dimension(600, 600));



        panelUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelUsuario.setOpaque(false);
        panelUsuario.setPreferredSize(new java.awt.Dimension(450, 600));

        Usuario1.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario1.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario1.setText("");
        Usuario1.setOpaque(true);
        Usuario1.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario2.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario2.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario2.setText("");
        Usuario2.setOpaque(true);
        Usuario2.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario3.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario3.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario3.setText("");
        Usuario3.setOpaque(true);
        Usuario3.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario4.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario4.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario4.setText("");
        Usuario4.setOpaque(true);
        Usuario4.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario5.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario5.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario5.setText("");
        Usuario5.setOpaque(true);
        Usuario5.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario6.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario6.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario6.setText("");
        Usuario6.setOpaque(true);
        Usuario6.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario7.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario7.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario7.setText("");
        Usuario7.setOpaque(true);
        Usuario7.setPreferredSize(new java.awt.Dimension(270, 40));

        Usuario8.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        Usuario8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Usuario8.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        Usuario8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuario8.setText("");
        Usuario8.setOpaque(true);
        Usuario8.setPreferredSize(new java.awt.Dimension(270, 40));

        javax.swing.GroupLayout panelUsuarioLayout = new javax.swing.GroupLayout(panelUsuario);
        panelUsuario.setLayout(panelUsuarioLayout);
        panelUsuarioLayout.setHorizontalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Usuario8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelUsuarioLayout.setVerticalGroup(
            panelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsuarioLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Usuario8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        flechaCargarUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        flechaCargarUsuarios.setText("-------->");
        flechaCargarUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flechaCargarUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaCargarUsuariosMouseClicked(evt);
            }
        });

        seleccionarUsuario.setBackground(new java.awt.Color(73, 128, 153));
        seleccionarUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seleccionarUsuario.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        seleccionarUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        seleccionarUsuario.setText("Seleccione usuario");
        seleccionarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seleccionarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarUsuarioMouseClicked(evt);
            }
        });
        seleccionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarUsuarioActionPerformed(evt);
            }
        });

        usuarioSeleccionado.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        usuarioSeleccionado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usuarioSeleccionado.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        usuarioSeleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuarioSeleccionado.setText("Usuario seleccionado");
        usuarioSeleccionado.setOpaque(true);

        darDeBajaButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        darDeBajaButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        darDeBajaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darDeBajaButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                darDeBajaButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                darDeBajaButtonMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dar de baja usuario");

        javax.swing.GroupLayout darDeBajaButtonLayout = new javax.swing.GroupLayout(darDeBajaButton);
        darDeBajaButton.setLayout(darDeBajaButtonLayout);
        darDeBajaButtonLayout.setHorizontalGroup(
            darDeBajaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        darDeBajaButtonLayout.setVerticalGroup(
            darDeBajaButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        cerrarSesionButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        cerrarSesionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarSesionButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarSesionButtonMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cerrar sesión");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout cerrarSesionButtonLayout = new javax.swing.GroupLayout(cerrarSesionButton);
        cerrarSesionButton.setLayout(cerrarSesionButtonLayout);
        cerrarSesionButtonLayout.setHorizontalGroup(
            cerrarSesionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );
        cerrarSesionButtonLayout.setVerticalGroup(
            cerrarSesionButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(flechaCargarUsuarios)))
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(darDeBajaButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cerrarSesionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuarioSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(seleccionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(usuarioSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(darDeBajaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cerrarSesionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addContainerGap(30, Short.MAX_VALUE)
                        .addComponent(panelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(flechaCargarUsuarios)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        

    private void flechaCargarUsuariosMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        j = cargarUsuariosLista(j);
    }                                                 

    private void seleccionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {                                                   
        
    }                                                  

    private void darDeBajaButtonMouseEntered(java.awt.event.MouseEvent evt) {                                             
        darDeBajaButton.setBackground(new Color(PaletaDeColores.BotonPresionado.R, PaletaDeColores.BotonPresionado.G, PaletaDeColores.BotonPresionado.B));
    }                                            

    private void darDeBajaButtonMouseExited(java.awt.event.MouseEvent evt) {                                            
        if(botonSeleccionado != darDeBajaButton){
            darDeBajaButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        }
    }                                           

    private void darDeBajaButtonMouseClicked(java.awt.event.MouseEvent evt) {                                             
        if(usuarioSeleccioando == null){
            usuarioSeleccioando = gestorUsuarios.buscarUsuarioAdmin(seleccionarUsuario.getText());
            if(usuarioSeleccioando == null){
                jLabel1.setText("Nombre Incorrecto");
            } else {
                usuarioSeleccionado.setText(usuarioSeleccioando.getNombre());
                if(usuarioSeleccioando.isCuentaActiva()){
                    jLabel1.setText("Dar de baja");
                } else {
                    jLabel1.setText("Habilitar");
                }
            }
        } else {
            if(usuarioSeleccioando.isCuentaActiva()){
                usuarioSeleccioando.setCuentaActiva(false);
                gestorUsuarios.cargarUsuarioJson(usuarioSeleccioando);
                usuarioSeleccioando = null;
                jLabel1.setText("Confirmar Busqueda");
            } else {
                usuarioSeleccioando.setCuentaActiva(true);
                gestorUsuarios.cargarUsuarioJson(usuarioSeleccioando);
                usuarioSeleccioando = null;
                jLabel1.setText("Confirmar Busqueda");
            }
        }
    }                                            

    private void seleccionarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {                                                
        seleccionarUsuario.setText("");
        jLabel1.setText("Confirmar Busqueda");
    }                                               

    private void cerrarSesionButtonMouseEntered(java.awt.event.MouseEvent evt) {                                                
        cerrarSesionButton.setBackground(new Color(PaletaDeColores.BotonPresionado.R, PaletaDeColores.BotonPresionado.G, PaletaDeColores.BotonPresionado.B));
    }                                               

    private void cerrarSesionButtonMouseExited(java.awt.event.MouseEvent evt) {                                               
        if(botonSeleccionado != cerrarSesionButton){
            cerrarSesionButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        }
    }                                              

    private void cerrarSesionButtonMouseClicked(java.awt.event.MouseEvent evt) {                                                
        mainFrame.showPanelLogin();
    }         
    
    
    public ArrayList<JLabel> iteradorLabelUsuario(){
        ArrayList<JLabel> it = new ArrayList<>();
        it.add(Usuario1);
        it.add(Usuario2);
        it.add(Usuario3);
        it.add(Usuario4);
        it.add(Usuario5);
        it.add(Usuario6);
        it.add(Usuario7);
        it.add(Usuario8);

        return it;
    }

    public int cargarUsuariosLista(int j){
        ArrayList<JLabel> labels = iteradorLabelUsuario();
        Collection<Usuario> it = gestorUsuarios.getHashMap().values();
        Iterator<Usuario> ite = it.iterator();
        int i = 0, k = 0;

        if(j!=0){
            while (k < j && ite.hasNext()) {
                ite.next();
                k++;
            }
        }

        while (i < labels.size() && ite.hasNext()) {
            Usuario aux = ite.next();
            labels.get(i).setText(aux.getNombre());
            i++;
            j++;
        }

        while(i < labels.size()){
            labels.get(i).setText("------");
            i++;
            j=0;
        }

        return j;

    }


    // Variables declaration - do not modify                     
    private javax.swing.JLabel Usuario1;
    private javax.swing.JLabel Usuario2;
    private javax.swing.JLabel Usuario3;
    private javax.swing.JLabel Usuario4;
    private javax.swing.JLabel Usuario5;
    private javax.swing.JLabel Usuario6;
    private javax.swing.JLabel Usuario7;
    private javax.swing.JLabel Usuario8;
    private javax.swing.JPanel background;
    private javax.swing.JPanel cerrarSesionButton;
    private javax.swing.JPanel darDeBajaButton;
    private javax.swing.JLabel flechaCargarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panelUsuario;
    private javax.swing.JTextField seleccionarUsuario;
    private javax.swing.JLabel usuarioSeleccionado;
    // End of variables declaration                   
}
