/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

/**
 *
 * @author Usuario
 */
public class PanelJuegosAdmin extends javax.swing.JPanel {

    /**
     * Creates new form PanelJuegosAdmin
     */
    public PanelJuegosAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        juego1 = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        juego2 = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        juego3 = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        juego4 = new javax.swing.JPanel();
        icon4 = new javax.swing.JLabel();
        juego5 = new javax.swing.JPanel();
        icon5 = new javax.swing.JLabel();
        juego6 = new javax.swing.JPanel();
        icon6 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JPanel();
        nombre1Label1 = new javax.swing.JLabel();
        nombre2 = new javax.swing.JPanel();
        nombre1Label = new javax.swing.JLabel();
        nombre3 = new javax.swing.JPanel();
        nombre1Label3 = new javax.swing.JLabel();
        nombre4 = new javax.swing.JPanel();
        nombre1Label4 = new javax.swing.JLabel();
        nombre5 = new javax.swing.JPanel();
        nombre1Label5 = new javax.swing.JLabel();
        nombre6 = new javax.swing.JPanel();
        nombre1Label2 = new javax.swing.JLabel();
        habilitarDeshabilitarButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        limpiarHistorialButton = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setPreferredSize(new java.awt.Dimension(600, 600));

        juego1.setBackground(new java.awt.Color(73, 128, 153));
        juego1.setMinimumSize(new java.awt.Dimension(150, 100));
        juego1.setPreferredSize(new java.awt.Dimension(150, 150));

        icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego1Layout = new javax.swing.GroupLayout(juego1);
        juego1.setLayout(juego1Layout);
        juego1Layout.setHorizontalGroup(
            juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        juego1Layout.setVerticalGroup(
            juego1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        juego2.setBackground(new java.awt.Color(73, 128, 153));
        juego2.setMinimumSize(new java.awt.Dimension(150, 100));
        juego2.setPreferredSize(new java.awt.Dimension(150, 150));

        icon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego2Layout = new javax.swing.GroupLayout(juego2);
        juego2.setLayout(juego2Layout);
        juego2Layout.setHorizontalGroup(
            juego2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        juego2Layout.setVerticalGroup(
            juego2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        juego3.setBackground(new java.awt.Color(73, 128, 153));
        juego3.setMinimumSize(new java.awt.Dimension(150, 100));
        juego3.setPreferredSize(new java.awt.Dimension(150, 150));

        icon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego3Layout = new javax.swing.GroupLayout(juego3);
        juego3.setLayout(juego3Layout);
        juego3Layout.setHorizontalGroup(
            juego3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        juego3Layout.setVerticalGroup(
            juego3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        juego4.setBackground(new java.awt.Color(73, 128, 153));
        juego4.setMinimumSize(new java.awt.Dimension(150, 100));
        juego4.setPreferredSize(new java.awt.Dimension(150, 150));

        icon4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego4Layout = new javax.swing.GroupLayout(juego4);
        juego4.setLayout(juego4Layout);
        juego4Layout.setHorizontalGroup(
            juego4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        juego4Layout.setVerticalGroup(
            juego4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon4, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        juego5.setBackground(new java.awt.Color(73, 128, 153));
        juego5.setMinimumSize(new java.awt.Dimension(150, 100));
        juego5.setPreferredSize(new java.awt.Dimension(150, 150));

        icon5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego5Layout = new javax.swing.GroupLayout(juego5);
        juego5.setLayout(juego5Layout);
        juego5Layout.setHorizontalGroup(
            juego5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon5, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        juego5Layout.setVerticalGroup(
            juego5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        juego6.setBackground(new java.awt.Color(73, 128, 153));
        juego6.setMinimumSize(new java.awt.Dimension(150, 100));
        juego6.setPreferredSize(new java.awt.Dimension(150, 150));

        icon6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout juego6Layout = new javax.swing.GroupLayout(juego6);
        juego6.setLayout(juego6Layout);
        juego6Layout.setHorizontalGroup(
            juego6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon6, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        juego6Layout.setVerticalGroup(
            juego6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(juego6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon6, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );

        nombre1.setBackground(new java.awt.Color(133, 36, 103));
        nombre1.setLayout(new java.awt.BorderLayout());

        nombre1Label1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        nombre1Label1.setForeground(new java.awt.Color(255, 255, 255));
        nombre1Label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1Label1.setText("Juego 1");
        nombre1.add(nombre1Label1, java.awt.BorderLayout.CENTER);

        nombre2.setBackground(new java.awt.Color(133, 36, 103));
        nombre2.setLayout(new java.awt.BorderLayout());

        nombre1Label.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        nombre1Label.setForeground(new java.awt.Color(255, 255, 255));
        nombre1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1Label.setText("Juego 2");
        nombre2.add(nombre1Label, java.awt.BorderLayout.CENTER);

        nombre3.setBackground(new java.awt.Color(133, 36, 103));
        nombre3.setLayout(new java.awt.BorderLayout());

        nombre1Label3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        nombre1Label3.setForeground(new java.awt.Color(255, 255, 255));
        nombre1Label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1Label3.setText("Juego 3");
        nombre3.add(nombre1Label3, java.awt.BorderLayout.CENTER);

        nombre4.setBackground(new java.awt.Color(133, 36, 103));
        nombre4.setLayout(new java.awt.BorderLayout());

        nombre1Label4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        nombre1Label4.setForeground(new java.awt.Color(255, 255, 255));
        nombre1Label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1Label4.setText("Juego 4");
        nombre4.add(nombre1Label4, java.awt.BorderLayout.CENTER);

        nombre5.setBackground(new java.awt.Color(133, 36, 103));
        nombre5.setLayout(new java.awt.BorderLayout());

        nombre1Label5.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        nombre1Label5.setForeground(new java.awt.Color(255, 255, 255));
        nombre1Label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1Label5.setText("Juego 5");
        nombre5.add(nombre1Label5, java.awt.BorderLayout.CENTER);

        nombre6.setBackground(new java.awt.Color(133, 36, 103));
        nombre6.setLayout(new java.awt.BorderLayout());

        nombre1Label2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
        nombre1Label2.setForeground(new java.awt.Color(255, 255, 255));
        nombre1Label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombre1Label2.setText("Juego 6");
        nombre6.add(nombre1Label2, java.awt.BorderLayout.CENTER);

        habilitarDeshabilitarButton.setBackground(new java.awt.Color(133, 36, 103));
        habilitarDeshabilitarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        habilitarDeshabilitarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitarDeshabilitarButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                habilitarDeshabilitarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                habilitarDeshabilitarButtonMouseExited(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Habilitar/Deshabilitar");

        javax.swing.GroupLayout habilitarDeshabilitarButtonLayout = new javax.swing.GroupLayout(habilitarDeshabilitarButton);
        habilitarDeshabilitarButton.setLayout(habilitarDeshabilitarButtonLayout);
        habilitarDeshabilitarButtonLayout.setHorizontalGroup(
            habilitarDeshabilitarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        habilitarDeshabilitarButtonLayout.setVerticalGroup(
            habilitarDeshabilitarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        limpiarHistorialButton.setBackground(new java.awt.Color(133, 36, 103));
        limpiarHistorialButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiarHistorialButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiarHistorialButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                limpiarHistorialButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                limpiarHistorialButtonMouseExited(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Limpiar historial");

        javax.swing.GroupLayout limpiarHistorialButtonLayout = new javax.swing.GroupLayout(limpiarHistorialButton);
        limpiarHistorialButton.setLayout(limpiarHistorialButtonLayout);
        limpiarHistorialButtonLayout.setHorizontalGroup(
            limpiarHistorialButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        limpiarHistorialButtonLayout.setVerticalGroup(
            limpiarHistorialButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(juego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(juego2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(juego3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(juego4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(juego5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(juego6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                        .addComponent(habilitarDeshabilitarButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(limpiarHistorialButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habilitarDeshabilitarButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limpiarHistorialButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(juego1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juego2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juego3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(juego4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juego5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(juego6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon1MouseClicked

    private void icon2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon2MouseClicked

    private void icon3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon3MouseClicked

    private void icon4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon4MouseClicked

    private void icon5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon5MouseClicked

    private void icon6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icon6MouseClicked

    private void habilitarDeshabilitarButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarDeshabilitarButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_habilitarDeshabilitarButtonMouseEntered

    private void habilitarDeshabilitarButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarDeshabilitarButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_habilitarDeshabilitarButtonMouseExited

    private void habilitarDeshabilitarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_habilitarDeshabilitarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_habilitarDeshabilitarButtonMouseClicked

    private void limpiarHistorialButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarHistorialButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarHistorialButtonMouseEntered

    private void limpiarHistorialButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarHistorialButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarHistorialButtonMouseExited

    private void limpiarHistorialButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiarHistorialButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiarHistorialButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel habilitarDeshabilitarButton;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel juego1;
    private javax.swing.JPanel juego2;
    private javax.swing.JPanel juego3;
    private javax.swing.JPanel juego4;
    private javax.swing.JPanel juego5;
    private javax.swing.JPanel juego6;
    private javax.swing.JPanel limpiarHistorialButton;
    private javax.swing.JPanel nombre1;
    private javax.swing.JLabel nombre1Label;
    private javax.swing.JLabel nombre1Label1;
    private javax.swing.JLabel nombre1Label2;
    private javax.swing.JLabel nombre1Label3;
    private javax.swing.JLabel nombre1Label4;
    private javax.swing.JLabel nombre1Label5;
    private javax.swing.JPanel nombre2;
    private javax.swing.JPanel nombre3;
    private javax.swing.JPanel nombre4;
    private javax.swing.JPanel nombre5;
    private javax.swing.JPanel nombre6;
    // End of variables declaration//GEN-END:variables
}
