/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package InterfazGrafica;

import java.awt.Color;
import java.util.ArrayList;
import java.util.LinkedList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

import Avatares.Cosmetico;
import Avatares.GestorCosmeticos;
import Interfaces.IterableElementosSwing;

/**
 *
 * @author Usuario
 */
public class PanelTiendaAdmin extends Panel implements IterableElementosSwing {

    private GestorCosmeticos gestorCosmeticos;
    private Cosmetico cosmeticoSeleccionado;
    private Integer index;

    public PanelTiendaAdmin() {
        initComponents();
        gestorCosmeticos = new GestorCosmeticos();
        this.botonSeleccionado = null;
        setBotonSeleccionado(gorroButton);
        mostrarCosmeticos(gestorCosmeticos.getGorros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgorund1 = new javax.swing.JPanel();
        trajeButton10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        gorroButton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lentesButton9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cosmetico1 = new javax.swing.JPanel();
        icon1 = new javax.swing.JLabel();
        Cosmetico2 = new javax.swing.JPanel();
        icon2 = new javax.swing.JLabel();
        Cosmetico3 = new javax.swing.JPanel();
        icon3 = new javax.swing.JLabel();
        Cosmetico4 = new javax.swing.JPanel();
        icon4 = new javax.swing.JLabel();
        Cosmetico5 = new javax.swing.JPanel();
        icon5 = new javax.swing.JLabel();
        Cosmetico6 = new javax.swing.JPanel();
        icon6 = new javax.swing.JLabel();
        Cosmetico7 = new javax.swing.JPanel();
        icon7 = new javax.swing.JLabel();
        Cosmetico8 = new javax.swing.JPanel();
        icon8 = new javax.swing.JLabel();
        habilitarDeshabilitarButton = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        confirmarCambioButton = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        backgorund1.setBackground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));

        trajeButton10.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        trajeButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trajeButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trajeButton10MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trajeButton10MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                trajeButton10MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Trajes");

        javax.swing.GroupLayout trajeButton10Layout = new javax.swing.GroupLayout(trajeButton10);
        trajeButton10.setLayout(trajeButton10Layout);
        trajeButton10Layout.setHorizontalGroup(
                trajeButton10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE));
        trajeButton10Layout.setVerticalGroup(
                trajeButton10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        gorroButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        gorroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gorroButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gorroButtonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gorroButtonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                gorroButtonMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gorros");

        javax.swing.GroupLayout gorroButtonLayout = new javax.swing.GroupLayout(gorroButton);
        gorroButton.setLayout(gorroButtonLayout);
        gorroButtonLayout.setHorizontalGroup(
                gorroButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE));
        gorroButtonLayout.setVerticalGroup(
                gorroButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        lentesButton9.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        lentesButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lentesButton9.setPreferredSize(new java.awt.Dimension(150, 40));
        lentesButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lentesButton9MouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lentesButton9MouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                lentesButton9MouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lentes");

        javax.swing.GroupLayout lentesButton9Layout = new javax.swing.GroupLayout(lentesButton9);
        lentesButton9.setLayout(lentesButton9Layout);
        lentesButton9Layout.setHorizontalGroup(
                lentesButton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE));
        lentesButton9Layout.setVerticalGroup(
                lentesButton9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        Cosmetico1.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico1.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico1.setPreferredSize(new java.awt.Dimension(120, 120));

        icon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico1Layout = new javax.swing.GroupLayout(Cosmetico1);
        Cosmetico1.setLayout(Cosmetico1Layout);
        Cosmetico1Layout.setHorizontalGroup(
                Cosmetico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico1Layout.createSequentialGroup()
                                .addComponent(icon1, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico1Layout.setVerticalGroup(
                Cosmetico1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon1, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico2.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico2.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico2.setPreferredSize(new java.awt.Dimension(120, 120));

        icon2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico2Layout = new javax.swing.GroupLayout(Cosmetico2);
        Cosmetico2.setLayout(Cosmetico2Layout);
        Cosmetico2Layout.setHorizontalGroup(
                Cosmetico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico2Layout.createSequentialGroup()
                                .addComponent(icon2, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico2Layout.setVerticalGroup(
                Cosmetico2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico3.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico3.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico3.setPreferredSize(new java.awt.Dimension(120, 120));

        icon3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico3Layout = new javax.swing.GroupLayout(Cosmetico3);
        Cosmetico3.setLayout(Cosmetico3Layout);
        Cosmetico3Layout.setHorizontalGroup(
                Cosmetico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico3Layout.createSequentialGroup()
                                .addComponent(icon3, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico3Layout.setVerticalGroup(
                Cosmetico3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon3, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico4.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico4.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico4.setPreferredSize(new java.awt.Dimension(120, 120));

        icon4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico4Layout = new javax.swing.GroupLayout(Cosmetico4);
        Cosmetico4.setLayout(Cosmetico4Layout);
        Cosmetico4Layout.setHorizontalGroup(
                Cosmetico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico4Layout.createSequentialGroup()
                                .addComponent(icon4, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico4Layout.setVerticalGroup(
                Cosmetico4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico5.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico5.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico5.setPreferredSize(new java.awt.Dimension(120, 120));

        icon5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico5Layout = new javax.swing.GroupLayout(Cosmetico5);
        Cosmetico5.setLayout(Cosmetico5Layout);
        Cosmetico5Layout.setHorizontalGroup(
                Cosmetico5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico5Layout.createSequentialGroup()
                                .addComponent(icon5, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico5Layout.setVerticalGroup(
                Cosmetico5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico6.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico6.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico6.setPreferredSize(new java.awt.Dimension(120, 120));

        icon6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico6Layout = new javax.swing.GroupLayout(Cosmetico6);
        Cosmetico6.setLayout(Cosmetico6Layout);
        Cosmetico6Layout.setHorizontalGroup(
                Cosmetico6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico6Layout.createSequentialGroup()
                                .addComponent(icon6, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico6Layout.setVerticalGroup(
                Cosmetico6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico7.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico7.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico7.setPreferredSize(new java.awt.Dimension(120, 120));

        icon7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico7Layout = new javax.swing.GroupLayout(Cosmetico7);
        Cosmetico7.setLayout(Cosmetico7Layout);
        Cosmetico7Layout.setHorizontalGroup(
                Cosmetico7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico7Layout.createSequentialGroup()
                                .addComponent(icon7, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico7Layout.setVerticalGroup(
                Cosmetico7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        Cosmetico8.setBackground(new java.awt.Color(73, 128, 153));
        Cosmetico8.setMinimumSize(new java.awt.Dimension(150, 100));
        Cosmetico8.setPreferredSize(new java.awt.Dimension(120, 120));

        icon8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icon8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Cosmetico8Layout = new javax.swing.GroupLayout(Cosmetico8);
        Cosmetico8.setLayout(Cosmetico8Layout);
        Cosmetico8Layout.setHorizontalGroup(
                Cosmetico8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(Cosmetico8Layout.createSequentialGroup()
                                .addComponent(icon8, javax.swing.GroupLayout.PREFERRED_SIZE, 120,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        Cosmetico8Layout.setVerticalGroup(
                Cosmetico8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon8, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE));

        habilitarDeshabilitarButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        habilitarDeshabilitarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                habilitarDeshabilitarButtonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                habilitarDeshabilitarButtonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                habilitarDeshabilitarButtonMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hab/deshab");

        javax.swing.GroupLayout habilitarDeshabilitarButtonLayout = new javax.swing.GroupLayout(
                habilitarDeshabilitarButton);
        habilitarDeshabilitarButton.setLayout(habilitarDeshabilitarButtonLayout);
        habilitarDeshabilitarButtonLayout.setHorizontalGroup(
                habilitarDeshabilitarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE));
        habilitarDeshabilitarButtonLayout.setVerticalGroup(
                habilitarDeshabilitarButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Cambiar precio");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        confirmarCambioButton.setBackground(new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        confirmarCambioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarCambioButtonMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmarCambioButtonMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                confirmarCambioButtonMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new Color(PaletaDeColores.ColorLetras.R, PaletaDeColores.ColorLetras.G, PaletaDeColores.ColorLetras.B));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Confirmar cambio");

        javax.swing.GroupLayout confirmarCambioButtonLayout = new javax.swing.GroupLayout(confirmarCambioButton);
        confirmarCambioButton.setLayout(confirmarCambioButtonLayout);
        confirmarCambioButtonLayout.setHorizontalGroup(
                confirmarCambioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE));
        confirmarCambioButtonLayout.setVerticalGroup(
                confirmarCambioButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE));

        javax.swing.GroupLayout backgorund1Layout = new javax.swing.GroupLayout(backgorund1);
        backgorund1.setLayout(backgorund1Layout);
        backgorund1Layout.setHorizontalGroup(
                backgorund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(backgorund1Layout.createSequentialGroup()
                                .addGroup(backgorund1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(backgorund1Layout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(gorroButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(lentesButton9, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(33, 33, 33)
                                                .addComponent(trajeButton10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(backgorund1Layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(backgorund1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Cosmetico1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Cosmetico5,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(backgorund1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Cosmetico2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Cosmetico6,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(backgorund1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Cosmetico3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Cosmetico7,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(30, 30, 30)
                                                .addGroup(backgorund1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Cosmetico4,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Cosmetico8,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(backgorund1Layout.createSequentialGroup()
                                                .addGap(100, 100, 100)
                                                .addComponent(habilitarDeshabilitarButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(backgorund1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(jTextField1)
                                                        .addComponent(confirmarCambioButton,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE))))
                                .addContainerGap(16, Short.MAX_VALUE)));
        backgorund1Layout.setVerticalGroup(
                backgorund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgorund1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(backgorund1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(gorroButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lentesButton9, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(trajeButton10, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(backgorund1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(backgorund1Layout.createSequentialGroup()
                                                .addGap(41, 41, 41)
                                                .addComponent(habilitarDeshabilitarButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgorund1Layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39,
                                                        Short.MAX_VALUE)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(confirmarCambioButton,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)))
                                .addGroup(
                                        backgorund1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Cosmetico2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cosmetico1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cosmetico3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cosmetico4, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(backgorund1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Cosmetico5, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cosmetico6, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cosmetico7, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Cosmetico8, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backgorund1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backgorund1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));
    }// </editor-fold>//GEN-END:initComponents

    private void trajeButton10MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_trajeButton10MouseClicked
        if (botonSeleccionado != trajeButton10) {
            setBotonSeleccionado(trajeButton10);
            mostrarCosmeticos(gestorCosmeticos.getTrajes());
        }
    }// GEN-LAST:event_trajeButton10MouseClicked

    private void trajeButton10MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_trajeButton10MouseEntered
        trajeButton10.setBackground(new Color(PaletaDeColores.BotonPresionado.R, PaletaDeColores.BotonPresionado.G,
                PaletaDeColores.BotonPresionado.B));
    }

    private void trajeButton10MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_trajeButton10MouseExited
        if (botonSeleccionado != trajeButton10) {
            trajeButton10.setBackground(
                    new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        }
    }// GEN-LAST:event_trajeButton10MouseExited

    private void gorroButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_gorroButtonMouseClicked
        if (botonSeleccionado != gorroButton) {
            setBotonSeleccionado(gorroButton);
            mostrarCosmeticos(gestorCosmeticos.getGorros());
        }
    }// GEN-LAST:event_gorroButtonMouseClicked

    private void gorroButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_gorroButtonMouseEntered
        gorroButton.setBackground(new Color(PaletaDeColores.BotonPresionado.R, PaletaDeColores.BotonPresionado.G,
                PaletaDeColores.BotonPresionado.B));
    }// GEN-LAST:event_gorroButtonMouseEntered

    private void gorroButtonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_gorroButtonMouseExited
        if (botonSeleccionado != gorroButton) {
            gorroButton.setBackground(
                    new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        }
    }// GEN-LAST:event_gorroButtonMouseExited

    private void lentesButton9MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lentesButton9MouseClicked
        if (botonSeleccionado != lentesButton9) {
            setBotonSeleccionado(lentesButton9);
            mostrarCosmeticos(gestorCosmeticos.getLentes());
        }
    }// GEN-LAST:event_lentesButton9MouseClicked

    private void lentesButton9MouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lentesButton9MouseEntered
        lentesButton9.setBackground(new Color(PaletaDeColores.BotonPresionado.R, PaletaDeColores.BotonPresionado.G,
                PaletaDeColores.BotonPresionado.B));
    }// GEN-LAST:event_lentesButton9MouseEntered

    private void lentesButton9MouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lentesButton9MouseExited
        if (botonSeleccionado != lentesButton9) {
            lentesButton9.setBackground(
                    new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
        }
    }// GEN-LAST:event_lentesButton9MouseExited

    private void icon1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon1MouseClicked
        setIconSeleccionado(icon1);
        cosmeticoSeleccionado = null;
        index = 0;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (1 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon1MouseClicked

    private void icon2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon2MouseClicked
        setIconSeleccionado(icon2);
        cosmeticoSeleccionado = null;
        index = 1;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (2 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon2MouseClicked

    private void icon3MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon3MouseClicked
        setIconSeleccionado(icon3);
        cosmeticoSeleccionado = null;
        index = 2;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (3 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon3MouseClicked

    private void icon4MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon4MouseClicked
        setIconSeleccionado(icon4);
        cosmeticoSeleccionado = null;
        index = 3;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (4 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon4MouseClicked

    private void icon5MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon5MouseClicked
        setIconSeleccionado(icon5);
        cosmeticoSeleccionado = null;
        index = 4;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (5 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon5MouseClicked

    private void icon6MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon6MouseClicked
        setIconSeleccionado(icon6);
        cosmeticoSeleccionado = null;
        index = 5;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (6 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon6MouseClicked

    private void icon7MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon7MouseClicked
        setIconSeleccionado(icon7);
        cosmeticoSeleccionado = null;
        index = 6;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (7 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon7MouseClicked

    private void icon8MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_icon8MouseClicked
        setIconSeleccionado(icon8);
        cosmeticoSeleccionado = null;
        index = 7;
        LinkedList<Cosmetico> aux = selecionarCosmetico(botonSeleccionado);
        if (8 <= aux.size()) {
            cosmeticoSeleccionado = aux.get(index);
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_icon8MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTextField1MouseClicked
       
    }// GEN-LAST:event_jTextField1MouseClicked

    private void habilitarDeshabilitarButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_habilitarDeshabilitarButtonMouseEntered
        habilitarDeshabilitarButton.setBackground(new Color(PaletaDeColores.BotonPresionado.R,
                PaletaDeColores.BotonPresionado.G, PaletaDeColores.BotonPresionado.B));
    }// GEN-LAST:event_habilitarDeshabilitarButtonMouseEntered

    private void habilitarDeshabilitarButtonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_habilitarDeshabilitarButtonMouseExited
        habilitarDeshabilitarButton.setBackground(
                new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
    }// GEN-LAST:event_habilitarDeshabilitarButtonMouseExited

    private void habilitarDeshabilitarButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_habilitarDeshabilitarButtonMouseClicked
        if (cosmeticoSeleccionado != null) {
            if (cosmeticoSeleccionado.isHabilitado()) {
                cosmeticoSeleccionado.setHabilitado(false);
            } else {
                cosmeticoSeleccionado.setHabilitado(true);
            }
            gestorCosmeticos.modificarCosmetico(cosmeticoSeleccionado, index);

            if (botonSeleccionado == gorroButton) {
                gestorCosmeticos.gorrosToJson();
            } else if (botonSeleccionado == lentesButton9) {
                gestorCosmeticos.lentesToJson();
            } else {
                gestorCosmeticos.trajesToJson();
            }
            cambiarTextoHab(cosmeticoSeleccionado);
        }
    }// GEN-LAST:event_habilitarDeshabilitarButtonMouseClicked

    private void confirmarCambioButtonMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_confirmarCambioButtonMouseEntered
        confirmarCambioButton.setBackground(new Color(PaletaDeColores.BotonPresionado.R,
                PaletaDeColores.BotonPresionado.G, PaletaDeColores.BotonPresionado.B));
    }// GEN-LAST:event_confirmarCambioButtonMouseEntered

    private void confirmarCambioButtonMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_confirmarCambioButtonMouseExited
        confirmarCambioButton.setBackground(
                new Color(PaletaDeColores.Botones.R, PaletaDeColores.Botones.G, PaletaDeColores.Botones.B));
    }// GEN-LAST:event_confirmarCambioButtonMouseExited

    private void confirmarCambioButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_confirmarCambioButtonMouseClicked
        if (cosmeticoSeleccionado != null) {

            String precioNuevo = jTextField1.getText();

            if (precioNuevo.matches("\\d+")) {
                cosmeticoSeleccionado.setPrecio(Long.valueOf(precioNuevo));

                gestorCosmeticos.modificarCosmetico(cosmeticoSeleccionado, index);

                if (botonSeleccionado == gorroButton) {
                    gestorCosmeticos.gorrosToJson();
                } else if (botonSeleccionado == lentesButton9) {
                    gestorCosmeticos.lentesToJson();
                } else {
                    gestorCosmeticos.trajesToJson();
                }
            }
        }
    }// GEN-LAST:event_confirmarCambioButtonMouseClicked

    public void cambiarTextoHab(Cosmetico cosmetico){
        if(cosmetico.isHabilitado()){
            jLabel4.setText("Deshabilitar");
        } else {
            jLabel4.setText("Habilitar");
        }
    }

    @Override
    public ArrayList<JLabel> iteradorElementosSwing() {
        ArrayList<JLabel> icons = new ArrayList<>();
        icons.add(icon1);
        icons.add(icon2);
        icons.add(icon3);
        icons.add(icon4);
        icons.add(icon5);
        icons.add(icon6);
        icons.add(icon7);
        icons.add(icon8);

        return icons;
    }

    public void mostrarCosmeticos(LinkedList<Cosmetico> cosmeticos) {
        ArrayList<JLabel> icons = iteradorElementosSwing();
        int i = 0, j = 0;

        while (i < icons.size() && j < cosmeticos.size()) {
            icons.get(i).setIcon(new ImageIcon(cosmeticos.get(j).getPathSprite()));
            i++;
            j++;
        }

        while (i < icons.size()) {

            icons.get(i).setIcon(new ImageIcon("src\\Avatares\\Sprites\\ArticuloNoDisponible.png"));
            i++;
        }
    }

    public LinkedList<Cosmetico> selecionarCosmetico(JPanel botonSeleccionado) {
        if (botonSeleccionado == gorroButton) {
            return gestorCosmeticos.getGorros();
        } else if (botonSeleccionado == lentesButton9) {
            return gestorCosmeticos.getLentes();
        } else {
            return gestorCosmeticos.getTrajes();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cosmetico1;
    private javax.swing.JPanel Cosmetico2;
    private javax.swing.JPanel Cosmetico3;
    private javax.swing.JPanel Cosmetico4;
    private javax.swing.JPanel Cosmetico5;
    private javax.swing.JPanel Cosmetico6;
    private javax.swing.JPanel Cosmetico7;
    private javax.swing.JPanel Cosmetico8;
    private javax.swing.JPanel backgorund1;
    private javax.swing.JPanel confirmarCambioButton;
    private javax.swing.JPanel gorroButton;
    private javax.swing.JPanel habilitarDeshabilitarButton;
    private javax.swing.JLabel icon1;
    private javax.swing.JLabel icon2;
    private javax.swing.JLabel icon3;
    private javax.swing.JLabel icon4;
    private javax.swing.JLabel icon5;
    private javax.swing.JLabel icon6;
    private javax.swing.JLabel icon7;
    private javax.swing.JLabel icon8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel lentesButton9;
    private javax.swing.JPanel trajeButton10;
    // End of variables declaration//GEN-END:variables
}
